### ISSUE TITLE
firestore CREDENTIALS Error when deploying firebase cloud function written in python

### ISSUE THREAD

**Issue by Daxitdon** [firebase/firebase-functions-python#126]
[REQUIRED] Environment info
firebase-tools:12.4.7

Platform: windows with python version of 3.11

[REQUIRED] Test case

i have code like below in for firebase cloud function in main.py. 
when i test function using `firebase emulators:start --only functions` it worked perfectly

now when i try to deploy it using `firebase deploy --only functions ` it gave me below error while pointing to     db = firestore.client()
line in code

error
"""""""""
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

"""""""""
code
"""
from firebase_functions import https_fn, options
import firebase_admin
from firebase_admin import firestore
app = firebase_admin.initialize_app()
options.set_global_options(timeout_sec=1000)

db = firestore.client()

### firebase function that write something to firestore database is written below
"""

[REQUIRED] Steps to reproduce

use above code in main.py inside functions folder and try to deploy functions you will get same error

[REQUIRED] Expected behavior

credential should be automatically added since i am logged into my account using firebase login and using correct Project ID. it did not ask for credential when i was tasing using `firebase emulators:start --only functions` and it was working perfectly.

[REQUIRED] Actual behavior

it's asking for credential

**Comment by LogansUA** [comment]
Hey, I'm actually having the same issue during `firebase deploy` in GitHub actions. I'm using 2 different ways setting service account creds for the action:
1. Using `google-github-actions/auth@v1`, like this:
```yml
- name: Authenticate to Google Cloud
  uses: google-github-actions/auth@v1
  with:
    credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'
```
2. Using `GOOGLE_APPLICATION_CREDENTIALS`, like this:
```yml
- name: Build Cloud Functions
  working-directory: functions
  env:
    SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
  run: |
    echo $SERVICE_ACCOUNT >> ./config.json

- name: Deploy Cloud Functions
  working-directory: .
  env:
    GOOGLE_APPLICATION_CREDENTIALS: './functions/config.json'
  run: npx firebase-tools deploy --only functions --debug
```
In both ways I'm getting the same error:
```
  File "/home/runner/work/family-finance/family-finance/functions/venv/lib/python3.11/site-packages/google/auth/_default.py", line 691, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

127.0.0.1 - - [01/Oct/2023 20:34:52] "GET /__/functions.yaml HTTP/1.1" 500 -

[2023-10-01T20:34:52.253Z] Got response code 500; body <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

127.0.0.1 - - [01/Oct/2023 20:34:52] "GET /__/quitquitquit HTTP/1.1" 200 -

Terminated
```

The interesting thing is that the 1st approach works for functions written using Node.js, I have a different repo with proper deploy setup through GH actions, which I thought I would be able to reuse with Python 🤷 
Before you ask, the `SERVICE_ACCOUNT` I'm using is properly generated in GCP Console with proper permissions.
