### ISSUE TITLE
Configure CPU-allocation, the run.googleapis.com/cpu-throttling boolean in Cloud Run 

### ISSUE THREAD

**Issue by antont** [firebase/firebase-functions-python#173]
Hi, is it possible to somehow configure the option that Cloud Run has for CPU allocation?

It's like this in the Run YAML:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: SERVICE
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'BOOLEAN'
      name: REVISION
```

where the bool is:

> BOOLEAN with true to set CPU allocation only during request processing, or false to set CPU to always allocated.

That's from https://cloud.google.com/run/docs/configuring/cpu-allocation#yaml

The Python lib here has many related options, such as cpu min-instances, and a way to set labels, but that `annotations` part is not mentioned in the docs, https://firebase.google.com/docs/reference/functions/2nd-gen/python/firebase_functions.options#firebase_functions.options.EventHandlerOptions
